/**
 * Analysis Note Pipeline — TypeScript Type Definitions
 *
 * These types mirror the canonical Analysis Note schema produced by
 * the Phase 1 ingestion pipeline. They are the frontend contract for
 * all Analysis Note data fetched from /api/ingestion/*.
 *
 * Principle: Business Reality, not accounting treatment.
 * No journal entries, no COA accounts, no debit/credit language.
 */

// ─────────────────────────────────────────────────────────────────────────────
// Enums
// ─────────────────────────────────────────────────────────────────────────────

export type DocumentType =
  | 'sales_invoice'
  | 'vendor_invoice'
  | 'customer_payment_receipt'
  | 'vendor_payment_receipt'
  | 'expense_receipt'
  | 'bank_statement'
  | 'credit_note'
  | 'debit_note'
  | 'purchase_order'
  | 'sales_order'
  | 'loan_agreement'
  | 'investment_agreement'
  | 'tax_document'
  | 'unknown';

export type EventType =
  | 'CUSTOMER_BILLED'
  | 'CUSTOMER_PAYMENT_RECEIVED'
  | 'VENDOR_BILLED'
  | 'VENDOR_PAYMENT_MADE'
  | 'EXPENSE_INCURRED'
  | 'PAYROLL_INCURRED'
  | 'REVENUE_REVERSED'
  | 'VENDOR_ADJUSTMENT_ISSUED'
  | 'BANK_ACTIVITY_RECORDED'
  | 'LOAN_RECEIVED'
  | 'INVESTMENT_RECEIVED'
  | 'TAX_LIABILITY_CREATED'
  | 'PURCHASE_ORDER_CREATED'
  | 'SALES_ORDER_CREATED'
  | 'UNCLASSIFIED';

export type CashDirection = 'INBOUND' | 'OUTBOUND' | 'MIXED' | 'NONE' | 'UNKNOWN';

export type ReviewStatus =
  | 'DRAFT'
  | 'UNDER_REVIEW'
  | 'APPROVED'
  | 'REJECTED'
  | 'SUPERSEDED';

export type ClassificationMethod = 'heuristic' | 'llm' | 'combined' | 'fallback';

export type ExtractionMethod =
  | 'gemini_vision'
  | 'groq_text'
  | 'aggregated'
  | 'fallback';

// ─────────────────────────────────────────────────────────────────────────────
// Three-Dimensional Confidence
// ─────────────────────────────────────────────────────────────────────────────

export interface AnalysisNoteConfidence {
  /** How cleanly the document was OCR-extracted. 0–1. */
  ocr_quality: number;
  /** How certain the classifier is about the document_type. 0–1. */
  classification: number;
  /** Fraction of required fields populated for this document type. 0–1. */
  field_completeness: number;
  /**
   * min(ocr_quality, classification, field_completeness).
   * One weak dimension poisons the whole note.
   * Routing: overall >= 0.85 → auto-route; < 0.85 → Needs Review.
   */
  overall: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// Event Candidate — Deterministic, no AI
// ─────────────────────────────────────────────────────────────────────────────

export interface EventCandidate {
  /**
   * Deterministic mapping from document_type via INTENT_MAP.
   * Never generated by AI. Always a lookup.
   */
  event_type: EventType;
  /**
   * Inherits classification confidence exactly.
   * No additional uncertainty introduced.
   */
  confidence: number;
  /** Always: "Deterministic mapping from document_type='...'" */
  reasoning: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Business Context — Business language only, no accounting terms
// ─────────────────────────────────────────────────────────────────────────────

export interface BusinessContext {
  /** What happened in the business. e.g. "CUSTOMER_BILLED" */
  intent: EventType;
  /** Direction of cash flow. */
  cash_direction: CashDirection;
  /** Plain English description of economic effect. */
  economic_effect: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Parties
// ─────────────────────────────────────────────────────────────────────────────

export interface Party {
  name:    string | null;
  gstin:   string | null;
  address: string | null;
}

export interface BankParty {
  bank_name:      string | null;
  account_holder: string | null;
  account_number: string | null;
  branch:         string | null;
  ifsc:           string | null;
}

export interface AnalysisNoteParties {
  issuer?:    Party | BankParty;
  recipient?: Party;
}

// ─────────────────────────────────────────────────────────────────────────────
// Amounts
// ─────────────────────────────────────────────────────────────────────────────

export interface InvoiceAmounts {
  subtotal:     number | null;
  tax_amount:   number | null;
  discount:     number | null;
  total_amount: number | null;
  currency:     string;
}

export interface BankStatementAmounts {
  opening_balance: number | null;
  closing_balance: number | null;
  total_credits:   number | null;
  total_debits:    number | null;
  net_cash_flow:   number | null;
  currency:        string;
}

export interface LoanAmounts extends InvoiceAmounts {
  principal_amount: number | null;
  interest_rate:    number | null;
}

export interface PayrollAmounts extends InvoiceAmounts {
  total_gross_pay:  number | null;
  total_deductions: number | null;
  total_net_pay:    number | null;
}

export type AnalysisNoteAmounts =
  | InvoiceAmounts
  | BankStatementAmounts
  | LoanAmounts
  | PayrollAmounts;

// ─────────────────────────────────────────────────────────────────────────────
// Dates
// ─────────────────────────────────────────────────────────────────────────────

export interface AnalysisNoteDates {
  document_date: string | null;   // ISO 8601
  due_date:      string | null;
  payment_date:  string | null;
  period_start:  string | null;
  period_end:    string | null;
}

// ─────────────────────────────────────────────────────────────────────────────
// References
// ─────────────────────────────────────────────────────────────────────────────

export interface AnalysisNoteReferences {
  invoice_number:        string | null;
  po_number:             string | null;
  so_number:             string | null;
  reference_invoice:     string | null;
  transaction_reference: string | null;
  agreement_number:      string | null;
  challan_number:        string | null;
  filing_period:         string | null;
  payroll_period:        string | null;
  loan_reference:        string | null;
  receipt_number:        string | null;
  account_number:        string | null;
  statement_period:      string | null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Line Items
// ─────────────────────────────────────────────────────────────────────────────

/** Generic line item for invoices, orders, receipts */
export interface GenericLineItem {
  description: string | null;
  quantity:    number | null;
  unit_price:  number | null;
  amount:      number | null;
  tax_rate:    number | null;
  tax_amount:  number | null;
}

/** Bank statement transaction */
export interface BankTransaction {
  transaction_date: string | null;
  description:      string | null;
  reference_number: string | null;
  debit:            number | null;
  credit:           number | null;
  balance:          number | null;
  counterparty:     string | null;
  payment_mode:     string | null;
  category:         string | null;
}

export type LineItem = GenericLineItem | BankTransaction;

// ─────────────────────────────────────────────────────────────────────────────
// Document Metadata
// ─────────────────────────────────────────────────────────────────────────────

export interface AnalysisNoteDocumentMetadata {
  document_id?:   string | null;
  document_date:  string | null;
  currency:       string;
  language:       string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Settlement (reconciliation data)
// ─────────────────────────────────────────────────────────────────────────────

export interface BankStatementSettlement {
  balance_verified:   boolean | null;
  difference:         number | null;
  expected_closing:   number | null;
  calculated_credits: number | null;
  calculated_debits:  number | null;
}

export type AnalysisNoteSettlement = BankStatementSettlement | Record<string, unknown>;

// ─────────────────────────────────────────────────────────────────────────────
// Master Analysis Note
// ─────────────────────────────────────────────────────────────────────────────

export interface AnalysisNote {
  /** UUID — primary key in analysis_notes table */
  id: string;

  /** FK to workbench_documents */
  document_id: string;

  /** FK to workbenches */
  workbench_id: string;

  /** Canonical document type. 'unknown' means pipeline halted. */
  document_type: DocumentType;

  /** Three-dimensional confidence. overall = min of all three. */
  confidence: AnalysisNoteConfidence;

  document_metadata: AnalysisNoteDocumentMetadata;
  parties:           AnalysisNoteParties;
  amounts:           AnalysisNoteAmounts;
  dates:             AnalysisNoteDates;
  document_references: AnalysisNoteReferences;
  business_context:  BusinessContext;
  line_items:        LineItem[];
  evidence:          Record<string, unknown>;
  settlement:        AnalysisNoteSettlement;

  /**
   * Cross-document linkage key.
   * Example: sales_invoice → "INV-1234"
   *          customer_payment_receipt for same invoice → "INV-1234"
   * Enables automatic invoice→payment→settlement matching.
   */
  settlement_key: string | null;

  /**
   * Deterministic event candidate. No AI involved.
   * Always a lookup from INTENT_MAP[document_type].
   */
  event_candidate: EventCandidate;

  /**
   * Lifecycle status.
   * Trade Engine acts on: APPROVED or (DRAFT with overall >= 0.85)
   */
  review_status: ReviewStatus;

  reviewed_by:   string | null;
  reviewed_at:   string | null;
  review_notes:  string | null;

  generator_version: string;

  /** True when a newer Analysis Note exists for this document. */
  is_superseded: boolean;

  created_at: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// OCR Raw Output
// ─────────────────────────────────────────────────────────────────────────────

export interface OCREntity {
  dates:         string[];
  amounts:       string[];
  organizations: string[];
  gstin_numbers: string[];
  bank_accounts: string[];
}

export interface OCRRawOutput {
  id:                 string;
  document_id:        string;
  workbench_id:       string;
  raw_text:           string;
  tables:             unknown[];
  entities:           OCREntity;
  extraction_method:  ExtractionMethod;
  page_count:         number;
  processing_time_ms: number | null;
  created_at:         string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Document Classification
// ─────────────────────────────────────────────────────────────────────────────

export interface DocumentClassification {
  id:                      string;
  document_id:             string;
  workbench_id:            string;
  document_type:           DocumentType;
  confidence:              number;
  reasoning:               string | null;
  classification_signals:  string[];
  classification_method:   ClassificationMethod;
  classifier_version:      string;
  created_at:              string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Processing Log
// ─────────────────────────────────────────────────────────────────────────────

export type ProcessingStage =
  | 'VALIDATE'
  | 'SPLIT'
  | 'OCR'
  | 'CLASSIFY'
  | 'ANALYSE'
  | 'QUEUE_TRADE'
  | 'COMPLETE'
  | 'ERROR';

export type ProcessingStatus = 'STARTED' | 'COMPLETED' | 'FAILED' | 'SKIPPED';

export interface ProcessingLogEntry {
  id:            string;
  document_id:   string;
  workbench_id:  string;
  stage:         ProcessingStage;
  status:        ProcessingStatus;
  duration_ms:   number | null;
  error_message: string | null;
  metadata:      Record<string, unknown>;
  created_at:    string;
}

// ─────────────────────────────────────────────────────────────────────────────
// API Response types
// ─────────────────────────────────────────────────────────────────────────────

export interface AnalysisNoteListResponse {
  data:  AnalysisNote[];
  count: number;
}

export interface SettlementKeyResponse {
  settlement_key: string;
  linked_notes:   Pick<AnalysisNote,
    'id' | 'document_id' | 'document_type' | 'settlement_key' | 'event_candidate' | 'amounts' | 'dates'
  >[];
  count: number;
}

export interface ReanalyseResponse {
  message:       string;
  analysis_note: AnalysisNote;
}

export interface ProcessingLogResponse {
  document_id: string;
  log:         ProcessingLogEntry[];
}
